project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
  output-dir: ../site

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    toc-location: left

website:
  title: "panGWAS"
  navbar:
    left:
      - text: Home
        href: index.qmd

      - text: Tutorials
        menu:
          - text: 01 - Test
            href: tutorials/01_test.md
          - text: 02 - Streptococcus pneumoniae
            href: tutorials/02_strep_pneumo.md
          - text: 03 - Pyseer Tutorial
            href: tutorials/03_pyseer_tutorial.md

      - text: Manual
        href: manual/table_of_contents.md

      - text: Pipeline
        href: pipeline/pipeline.md

      - text: Code Coverage
        href: coverage/index.html

      - text: Developers
        href: developers/developers.md
