name: Docs

# Workflow conditions
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:

  # ---------------------------------------------------------------------------
  #  Run the tests to get code coverage first
  test:
    uses: ./.github/workflows/test.yaml

  # ---------------------------------------------------------------------------          
  render:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          generate-run-shell: true
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'
          environment-name: quarto
          create-args: >-
            quarto=1.5.57

      - name: Download Code Coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: .

      - name: Render
        shell: micromamba-shell {0}
        run: |
          mv coverage docs/
          quarto render docs
          mv docs/coverage/* site/coverage/

      - name: Upload Site
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: site/
          retention-days: 7
          if-no-files-found: error
