# Re-usable workflow to create the website documentation
name: Docs

# Workflow conditions
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  # ---------------------------------------------------------------------------          
  render:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          generate-run-shell: true
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'
          environment-name: quarto
          create-args: >-
            quarto=1.5.57

      - name: Download Code Coverage
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: test.yml
          workflow_conclusion: success
          name: coverage
          path: coverage/
  
      # - name: Download Code Coverage
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: coverage
      #     path: coverage/

      - name: Render
        shell: micromamba-shell {0}
        run: |
          mv coverage docs/
          quarto render docs
          mv docs/coverage/* site/coverage/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: site/
          retention-days: 7
          if-no-files-found: error

  # ---------------------------------------------------------------------------          
  deploy:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Download Artifact
        uses: actions/download-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: site
          path: public/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          folder: public