name: Public

on:
  workflow_call:

env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ github.token }}
  DOCKER_IMAGE: "ghcr.io/${{ github.repository }}"

jobs:

  # ---------------------------------------------------------------------------          
  micromamba:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'
          condarc: |
            channels:
              - conda-forge
              - bioconda
          create-args: >-
            pangwas
