name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  #----------------------------------------------------------------------------
  release:

    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          draft: true
          generateReleaseNotes: true
          makeLatest: true
          prerelease: true