name: Test

# Workflow conditions
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:

  python:
    uses: ./.github/workflows/python.yaml

  nextflow:
    uses: ./.github/workflows/python.yaml

  # public:
  #   uses: ./.github/workflows/public.yaml

